

name: Deploy to Railway #name of a Workflow (will be visible in Git Hub actions)
#adding a trigger (when the Workflow will start doing smth..)
# trigger - when we have a push to "main"
on:
  push:
    branches:
      - main

# adding actions,
# what actions Git Hub will do after the trigger
jobs:
  deploy: # це просто identifier (ID) job.
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code #склонуй репозиторій на VM Гіт Хаба
        uses: actions/checkout@v3 


    #наступний код не треба, бо я передумав юзати токен,
    # та й тут не треба розгортати railway так як він сам задеплоїться,
    #бо є веб-хук від railway коли я роблю пуш в гітхаб
#jobs:
  #deploy:
   # runs-on: ubuntu-latest #git gub actions will create a temp Linux server, it will do the next actions
    #steps:
     # - name: Checkout code
      #  uses: actions/checkout@v3
      #- name: Install Railway CLI
       # run: npm install -g @railway/cli

     # - name: Deploy to Railway
      #  run: railway up
       # env: 
        #  RAILWAY_TOKEN: 
          





           





 

